spring:
  # app 이름
  application:
    name: demo
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##project
    password: project1234
  # Elasticsearch 설정
  elasticsearch:
    uris: http://localhost:9201
    connection-timeout: 30s
    socket-timeout: 30s

# 웹서버 포트
server:
  port: 9080

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    root: info

elasticsearch:
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}
  scheme: ${ES_SCHEME:http}